/home/groups/rbaltman/samori/miniconda3/condabin/conda: line 3: import: command not found
/home/groups/rbaltman/samori/miniconda3/condabin/conda: line 6: syntax error near unexpected token `sys.argv'
/home/groups/rbaltman/samori/miniconda3/condabin/conda: line 6: `if len(sys.argv) > 1 and sys.argv[1].startswith('shell.') and sys.path and sys.path[0] == '':'
Traceback (most recent call last):
  File "/home/users/iasamori/tiktok/download_comments_slurm/download_comments.py", line 24, in <module>
    main()
  File "/home/users/iasamori/tiktok/download_comments_slurm/download_comments.py", line 21, in main
    get_comments(video_ids, fields, cursor, save_folder)
  File "/home/users/iasamori/tiktok/download_comments_slurm/utils.py", line 131, in get_comments
    status_code = query_comments_api_paginate(fields, cursor, video_id, save_folder, log_name, credentials)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/iasamori/tiktok/download_comments_slurm/utils.py", line 71, in query_comments_api_paginate
    access_token = credentials["access_token"]
                   ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'
